# Generated by Django 5.0 on 2023-12-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='image')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog')], max_length=15)),
                ('color', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('disc', models.CharField(max_length=80)),
                ('price', models.BigIntegerField()),
            ],
        ),
    ]
